import { db } from '@/db';
import { achievements } from '@/db/schema';

async function main() {
    const sampleAchievements = [
        {
            name: 'First Steps',
            description: 'Complete your first 5 tasks and begin your productivity journey',
            icon: '🎯',
            badgeType: 'milestone',
            unlockCriteria: { type: 'tasks_completed', value: 5 },
            points: 10,
            tier: 'bronze',
            createdAt: new Date('2024-01-01').toISOString(),
        },
        {
            name: 'Getting Started',
            description: 'Complete 10 tasks and show consistency',
            icon: '🚀',
            badgeType: 'milestone',
            unlockCriteria: { type: 'tasks_completed', value: 10 },
            points: 20,
            tier: 'bronze',
            createdAt: new Date('2024-01-01').toISOString(),
        },
        {
            name: 'Task Master',
            description: 'Complete 50 tasks and prove your dedication',
            icon: '💪',
            badgeType: 'milestone',
            unlockCriteria: { type: 'tasks_completed', value: 50 },
            points: 50,
            tier: 'silver',
            createdAt: new Date('2024-01-01').toISOString(),
        },
        {
            name: 'Century Club',
            description: 'Join the elite with 100 completed tasks',
            icon: '💯',
            badgeType: 'milestone',
            unlockCriteria: { type: 'tasks_completed', value: 100 },
            points: 100,
            tier: 'gold',
            createdAt: new Date('2024-01-01').toISOString(),
        },
        {
            name: 'Elite Achiever',
            description: 'Reach legendary status with 500 completed tasks',
            icon: '👑',
            badgeType: 'milestone',
            unlockCriteria: { type: 'tasks_completed', value: 500 },
            points: 500,
            tier: 'platinum',
            createdAt: new Date('2024-01-01').toISOString(),
        },
        {
            name: 'Week Warrior',
            description: 'Maintain a 7-day streak of daily task completion',
            icon: '🔥',
            badgeType: 'streak',
            unlockCriteria: { type: 'streak', value: 7 },
            points: 70,
            tier: 'silver',
            createdAt: new Date('2024-01-01').toISOString(),
        },
        {
            name: 'Month Master',
            description: 'Achieve an incredible 30-day streak',
            icon: '⚡',
            badgeType: 'streak',
            unlockCriteria: { type: 'streak', value: 30 },
            points: 300,
            tier: 'gold',
            createdAt: new Date('2024-01-01').toISOString(),
        },
        {
            name: 'Unstoppable',
            description: 'Reach the ultimate 100-day streak milestone',
            icon: '🏆',
            badgeType: 'streak',
            unlockCriteria: { type: 'streak', value: 100 },
            points: 1000,
            tier: 'platinum',
            createdAt: new Date('2024-01-01').toISOString(),
        },
        {
            name: 'Daily Dozen',
            description: 'Complete 12 tasks in a single day',
            icon: '⭐',
            badgeType: 'milestone',
            unlockCriteria: { type: 'tasks_today', value: 12 },
            points: 60,
            tier: 'silver',
            createdAt: new Date('2024-01-01').toISOString(),
        },
        {
            name: 'Power User',
            description: 'Complete 50 tasks in one week',
            icon: '💎',
            badgeType: 'milestone',
            unlockCriteria: { type: 'tasks_week', value: 50 },
            points: 250,
            tier: 'gold',
            createdAt: new Date('2024-01-01').toISOString(),
        },
        {
            name: 'Early Bird',
            description: 'Complete your first task before 8am',
            icon: '🌅',
            badgeType: 'special',
            unlockCriteria: { type: 'special', value: 'early_bird' },
            points: 25,
            tier: 'bronze',
            createdAt: new Date('2024-01-01').toISOString(),
        },
        {
            name: 'Night Owl',
            description: 'Complete 5 tasks after 10pm',
            icon: '🦉',
            badgeType: 'special',
            unlockCriteria: { type: 'special', value: 'night_owl' },
            points: 25,
            tier: 'bronze',
            createdAt: new Date('2024-01-01').toISOString(),
        },
        {
            name: 'Productive Day',
            description: 'Complete 20 tasks in a single day',
            icon: '🎊',
            badgeType: 'milestone',
            unlockCriteria: { type: 'tasks_today', value: 20 },
            points: 100,
            tier: 'gold',
            createdAt: new Date('2024-01-01').toISOString(),
        },
        {
            name: 'Sprint Champion',
            description: 'Complete an amazing 100 tasks in one week',
            icon: '🥇',
            badgeType: 'milestone',
            unlockCriteria: { type: 'tasks_week', value: 100 },
            points: 500,
            tier: 'platinum',
            createdAt: new Date('2024-01-01').toISOString(),
        },
        {
            name: 'Legendary',
            description: 'Achieve the ultimate milestone of 1000 completed tasks',
            icon: '🌟',
            badgeType: 'milestone',
            unlockCriteria: { type: 'tasks_completed', value: 1000 },
            points: 2000,
            tier: 'platinum',
            createdAt: new Date('2024-01-01').toISOString(),
        },
        {
            name: 'Quick Starter',
            description: 'Complete 3 tasks within your first hour',
            icon: '⚡',
            badgeType: 'special',
            unlockCriteria: { type: 'special', value: 'quick_starter' },
            points: 30,
            tier: 'bronze',
            createdAt: new Date('2024-01-02').toISOString(),
        },
        {
            name: 'Weekend Warrior',
            description: 'Complete 20 tasks over a weekend',
            icon: '🎯',
            badgeType: 'special',
            unlockCriteria: { type: 'special', value: 'weekend_warrior' },
            points: 75,
            tier: 'silver',
            createdAt: new Date('2024-01-02').toISOString(),
        },
        {
            name: 'Consistent Contributor',
            description: 'Complete at least 5 tasks daily for 14 days',
            icon: '📈',
            badgeType: 'streak',
            unlockCriteria: { type: 'streak', value: 14 },
            points: 140,
            tier: 'silver',
            createdAt: new Date('2024-01-03').toISOString(),
        },
        {
            name: 'Marathon Runner',
            description: 'Maintain a 60-day streak of productivity',
            icon: '🏃',
            badgeType: 'streak',
            unlockCriteria: { type: 'streak', value: 60 },
            points: 600,
            tier: 'gold',
            createdAt: new Date('2024-01-03').toISOString(),
        },
        {
            name: 'Perfect Week',
            description: 'Complete your daily goal every day for a week',
            icon: '✨',
            badgeType: 'special',
            unlockCriteria: { type: 'special', value: 'perfect_week' },
            points: 150,
            tier: 'gold',
            createdAt: new Date('2024-01-04').toISOString(),
        }
    ];

    await db.insert(achievements).values(sampleAchievements);
    
    console.log('✅ Achievements seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});